INSERT INTO roles VALUES (1, 'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles VALUES (2, 'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles VALUES (3, 'ROLE_AD_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles VALUES (4, 'ROLE_INFO_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles VALUES (5, 'ROLE_REPORTER') ON CONFLICT DO NOTHING;

