INSERT INTO roles (id, name) VALUES (1, 'ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, name) VALUES (2, 'ROLE_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, name) VALUES (3, 'ROLE_AD_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, name) VALUES (4, 'ROLE_INFO_MANAGER') ON CONFLICT DO NOTHING;
INSERT INTO roles (id, name) VALUES (5, 'ROLE_REPORTER') ON CONFLICT DO NOTHING;

INSERT INTO prices VALUES (1, 990, 0) ON CONFLICT DO NOTHING;
INSERT INTO prices VALUES (2, 1990, 1) ON CONFLICT DO NOTHING;
INSERT INTO prices VALUES (3, 4990, 2) ON CONFLICT DO NOTHING;
INSERT INTO prices VALUES (4, 390, 3) ON CONFLICT DO NOTHING;

